# Canonical label definitions for jafreck/CADRE.
# Synced automatically by .github/workflows/label-sync.yml on every push to main
# that modifies this file. Run manually via: Actions → Label Sync → Run workflow.
#
# To add/rename/delete a label: edit this file and merge to main.
#
# NOTE: All color values are quoted strings to prevent YAML from interpreting
# hex codes as numbers (e.g. 5319E7 → scientific notation, 008672 → integer).

# ── Type ──────────────────────────────────────────────────────────────────────

- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: enhancement
  color: "a2eeef"
  description: New feature or request

- name: documentation
  color: "0075ca"
  description: Improvements or additions to documentation

- name: refactor
  color: "fbefb4"
  description: Code restructuring with no behavior change

- name: testing
  color: "c5def5"
  description: Test coverage or test infrastructure

# ── Priority ──────────────────────────────────────────────────────────────────

- name: "priority: critical"
  color: "b60205"
  description: Blocks usage or data loss — fix immediately

- name: "priority: high"
  color: "e4140a"
  description: High priority — address in current cycle

- name: "priority: medium"
  color: "FBCA04"
  description: Medium priority — address soon

- name: "priority: low"
  color: "c2e0c6"
  description: Low priority — nice to have

# ── Domain ────────────────────────────────────────────────────────────────────

- name: pipeline
  color: "0E8A16"
  description: Issues related to the cadre pipeline execution

- name: dogfooding
  color: "5319E7"
  description: Issues identified from cadre self-hosting runs

- name: cadre-generated
  color: "0075ca"
  description: Pull request automatically generated by cadre

# ── Status ────────────────────────────────────────────────────────────────────

- name: good first issue
  color: "7057ff"
  description: Good for newcomers

- name: help wanted
  color: "008672"
  description: Extra attention is needed

- name: question
  color: "d876e3"
  description: Further information is requested

- name: duplicate
  color: "cfd3d7"
  description: This issue or pull request already exists

- name: invalid
  color: "e4e669"
  description: This doesn't seem right

- name: wontfix
  color: "ffffff"
  description: This will not be worked on
